title: Каталог услуг
extends: page
admin-description: Каталог продукции
style: 'color:#d02ce8; font-weight:600'

areas:
    # Static params
	type:
        caption: "Тип страницы"
        type: int(11)
        editor: integer
        value: 1
        systemtype: static

	template:
        caption: "Шаблон"
        type: text
        editor: linetext
        value: innerCatalog
        systemtype: static

	modules:
        caption: "Модули"
        type: text
        editor: linetext
        value: main, services
        systemtype: static

	child_units:
        caption: "Unit-ы для дочерних элементов"
        type: text
        editor: linetext
        value: services_category,services_item
        systemtype: static

    # Post functions for areas. area = function
	pre_func:
        caption: "Пост обработчики полей"
        type: text
        editor: text
        value: |
          url = auto_url
        systemtype: static

	# Native params
	content_desc:
        caption: "Описание контент"
        desc: "Краткое описание страницы"
        type: text
        editor: linetext
        style: "width:800px"
